# Generated by Django 4.0.4 on 2022-05-12 17:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_supermarket', '0004_rename_id_supermarket_id_sup'),
    ]

    operations = [
        migrations.AddField(
            model_name='supermarket',
            name='confirm_password',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supermarket',
            name='sms',
            field=models.IntegerField(choices=[(1111, '1111')], default=datetime.date),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='supermarket',
            name='owner',
            field=models.TextField(blank=True, max_length=250),
        ),
    ]
