# Generated by Django 4.0.4 on 2022-05-12 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register_supermarket', '0006_remove_supermarket_confirm_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supermarket',
            name='from_hour',
        ),
        migrations.RemoveField(
            model_name='supermarket',
            name='to_hour',
        ),
    ]
