# Generated by Django 4.0.4 on 2022-04-22 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register_supermarket', '0003_rename_id_sup_supermarket_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supermarket',
            old_name='id',
            new_name='id_sup',
        ),
    ]
