# Generated by Django 4.0.1 on 2022-05-04 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='comments',
            new_name='description',
        ),
    ]
