# Generated by Django 4.0.1 on 2022-05-07 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0003_category_product_production_date_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supermarket.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='production_date',
            field=models.DateField(),
        ),
    ]
