# Generated by Django 4.0.4 on 2022-04-22 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register_customer', '0002_remove_customer_id_alter_customer_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='last_name',
            new_name='id',
        ),
    ]
