# Generated by Django 4.0.4 on 2022-04-22 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register_customer', '0003_rename_last_name_customer_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='id',
            new_name='last_name',
        ),
    ]
