# Generated by Django 4.0.4 on 2022-04-29 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_customer', '0005_alter_customer_options_customer_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
